export enum JobComplementEnum {
  ARMADOR = "Armador",
  CARPINTEIRO = "Carpinteiro",
  PEDREIRO = "Pedreiro",
  PINTOR = "Pintor",
  GESSEIRO = "Gesseiro",
  ELETRICISTA = "Eletricista",
  SOLDADOR = "Soldador",
  SERRALHEIRO = "Serralheiro",
  OBRAS = "Obras",
  ALMOXARIFADO = "Almoxarifado",
  ENCANAMENTO = "Encanador",
  MANUTENCAO_PREDIAL = "Manutenção Predial",
  MECANICO = "Mecânico",
}