export enum JobEnum {
  ALMOXARIFE = "Almoxarife",
  APONTADOR = "Apontador",
  ELETRICISTA = "Eletricista",
  ENCANADOR = "Encanador",
  VIGIA = "Vigia",
  MOTOBOY = "Motoboy",
  MOTORISTA_B = "Motorista (Cat. B)",
  MOTORISTA_D = "Motorista (Cat. D)",
  OPERADOR_TRATOR = "Operador de Trator",
  ASSISTENTE_ADMIN = "Assistente Administrativo",
  DESENVOLVEDOR = "Desenvolvedor",
  ENCARREGADO = "Encarregado",
  MEIO_OFICIAL = "Meio-Oficial",
  AUXILIAR = "Auxiliar",
  AJUDANTE = "Ajudante",
  PROFISSIONAL = "Profissional",
  TECNICO = "Técnico",
  MECANICO = "Mecânico",
}