export enum JobEnum {
  ALMOXARIFE = "Almoxarife",
  APONTADOR = "Apontador",
  ELETRICISTA = "Eletricista",
  ENCANADOR = "Encanador",
  VIGIA = "Vigia",
  MOTOBOY_I = "Motoboy - Nível I",
  MOTOBOY_II = "Motoboy - Nível II",
  MOTOBOY_III = "Motoboy - Nível III",
  OPERADOR_TRATOR_I = "Operador de Trator - Nível I",
  OPERADOR_TRATOR_II = "Operador de Trator - Nível II",
  OPERADOR_TRATOR_III = "Operador de Trator - Nível III",
  ASSISTENTE_ADMIN_JUNIOR = "Assistente Administrativo Júnior",
  ASSISTENTE_ADMIN_PLENO = "Assistente Administrativo Pleno",
  ASSISTENTE_ADMIN_SENIOR = "Assistente Administrativo Sênior",
  DESENVOLVEDOR_JUNIOR = "Desenvolvedor Junior",
  DESENVOLVEDOR_PLENO = "Desenvolvedor Pleno",
  DESENVOLVEDOR_SENIOR = "Desenvolvedor Senior",
  ENCARREGADO = "Encarregado",
  MEIO_OFICIAL = "Meio-Oficial",
  AUXILIAR = "Auxiliar",
  AJUDANTE = "Ajudante",
  PROFISSIONAL = "Profissional",
  TECNICO = "Técnico",
  MECANICO = "Mecânico",
}